version: '3'
services: 
  mongo:
    # restart: always
    image: mongo:latest
    container_name: lagabu_mongodb
    command: [--auth]
    ports:
      - 37017:27017
    volumes:
      - /data/db

  redis:
    image: redis:latest
    container_name: lagabu_redis
    ports: 
      - 6378:6379
    volumes:
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
    command:
      redis-server
    