version: '3'
services: 
  mongo:
    # restart: always
    image: mongo:latest
    container_name: lagabu_mongodb
    command: [--auth]
    ports:
      - 37017:27017
    volumes:
      - ${MONGODB_DIR}/data/db:/data/db

  redis:
    image: redis:latest
    container_name: lagabu_redis
    ports: 
      - 6378:6379
    volumes:
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
    command:
      redis-server

  mysql:
    image: mysql:latest
    container_name: lagabu_mysql
    ports:
      - 3307:3306
    volumes:
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    